### ISSUE TITLE
How does downsample_cells work

### ISSUE THREAD

**Issue by Evenlyeven** [rnabioco/scbp#4]
Thanks for developing this useful tool!

I wanted to know how downsample_cells function works, but I didn't find it. Could you share more information about how downsample_cells process is achieved?

Thanks!

**Comment by kriemo** [comment]
hi, glad you find the code useful. The `downsample_cells()` function randomly samples a subset of cells from each level of a grouping variable in the metadata (e.g. clusters, cell-type, replicate). 

Here's the source code
https://github.com/rnabioco/scbp/blob/92d3dd2d59cbf9dd038d9a772e5a11f885ceb5fe/R/utils.R#L1436
